name: splatsim
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile=1.1.2
  - python=3.12.11
  - pip==25.1.1
  - tqdm==4.67.1
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn